### ISSUE TITLE
Can't run it on xCode 9.3

### ISSUE THREAD

**Issue by psi-gh** [apollographql/xcode-graphql#10]
After update to 9.3 plugin appears to be turned off. I tried to reinstall it, without success.

**Comment by martijnwalraven** [comment]
Every Xcode update requires adding the new UUID to the plugin. This should be fixed in https://github.com/apollographql/xcode-graphql/commit/e5bf4c0b52af45c1f2c11f7dea34f58bdd33c099.

**Comment by psi-gh** [comment]
@martijnwalraven Thank you.
