### ISSUE TITLE
Broken for Xcode 10.3, need to add UUID?

### ISSUE THREAD

**Issue by attheodo** [apollographql/xcode-graphql#21]
Looks like the integration is broken for the latest Xcode. Historically it seems adding the UUID fixes the issue.

**Comment by designatednerd** [comment]
Yeah we had #20 fixing it, but the contributor didn't to sign our contributor agreement so I couldn't merge it. 

I just closed that PR and committed the new UUID straight to `master`. Installed locally and confirmed it's working with Xcode 10.3. 

Gonna close this out, please reopen if you run into any problems. Thank you!
