### ISSUE TITLE
Xcode 11.4 (11E146)

### ISSUE THREAD

**Issue by attheodo** [apollographql/xcode-graphql#28]
Looks like the plugin is not working for this particular version. Loaded bundle after `./setup.sh` but still no highlighting.

**Comment by designatednerd** [comment]
Highlighting's definitely working on my end in 11.4: 

<img width="545" alt="Screen Shot 2020-04-07 at 10 47 36 AM" src="https://user-images.githubusercontent.com/1976498/78690641-56e19d80-78bd-11ea-9b04-4ad9981bbf6d.png">

In the past when I've had issues with this, I've deleted the old version and reinstalled. Remember that it won't work until you restart Xcode AND allow the plugin to be loaded.

**Comment by attheodo** [comment]
Oh, that's weird. Yeah restarted and allowed plugin to be loaded. So I just delete the items that `setup.sh` is creating and then try again?

**Comment by designatednerd** [comment]
that'd be my recommendation. also make sure you have the most recent code which has the Xcode 11.4 UUID in it

**Comment by attheodo** [comment]
Looks like I didn't pay too much attention on the output of `setup.sh` 

`cp: /Applications/Xcode.app/Contents/SharedFrameworks/SourceModel.framework/Versions/A/Resources/LanguageSpecifications/GraphQL.xclangspec: Permission denied
cp: /Applications/Xcode.app/Contents/SharedFrameworks/SourceModel.framework/Versions/A/Resources/LanguageMetadata/Xcode.SourceCodeLanguage.GraphQL.plist: Permission denied`

Looks like there's a permissioning problem.

**Comment by designatednerd** [comment]
Are you using `sudo`?

**Comment by attheodo** [comment]
Am I? Of course I am not...

Also just catched this from the docs...

> `Particularly if you are running Catalina, you will need to use sudo in order to make this work due to changes in the permissions model.`

Disregard and carry one the good work :)
