### ISSUE TITLE
Version 11.4.1 (11E503a)

### ISSUE THREAD

**Issue by soyombo-baterdene** [apollographql/xcode-graphql#30]
Not working on Version 11.4.1 (11E503a).   I ran  sudo ./setup.sh and restarted xcode but not highlighting.

**Comment by designatednerd** [comment]
This is definitely working on my end, as seen in this screenshot:

<img width="407" alt="Screen Shot 2020-04-29 at 10 38 53 AM" src="https://user-images.githubusercontent.com/1976498/80615728-a8390480-8a05-11ea-8cfe-48967c0cc920.png"> 

We've seen a couple instances where you need to uninstall/reinstall the plugin to get it to cooperate after an update, though - can you please give that a try?

**Comment by designatednerd** [comment]
Closing this out since I haven't heard back from a while and 11.5 is out now

**Comment by designatednerd** [comment]
(also 11.5 has the same UUID as 11.4, so the procedure should be the same).
