### ISSUE TITLE
Xcode 11.5/11.6 Compatible

### ISSUE THREAD

**Issue by designatednerd** [apollographql/xcode-graphql#31]
This plugin works with Xcode 11.5 because the UUID for that version is identical to 11.4. If you're having any trouble, please run the installer again. Thank you!

_Edit, 7/15: Also with Xcode 11.6, still the same UUID_

**Comment by CarmenFJW** [comment]
I've tried running the installer again, but it doesn't seem to work. =(

**Comment by designatednerd** [comment]
Hi! Make sure you're running with `sudo` and give it another shot. I've definitely seen a couple instances where the setup doesn't quite work the first time. 

You also can run `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID` locally to validate that the plugin compatibility UUID is still `C80A9C11-3902-4885-944E-A035869BA910`, which is [already in the plist of compatible UUIDs](https://github.com/apollographql/xcode-graphql/blob/master/GraphQL.ideplugin/Contents/Info.plist#L47).

**Comment by matvdg** [comment]
Hi, @designatednerd it still doesn't work anymore on Xcode 11.5, I checked the UUID still unchanged, I retried several times to launch the setup with sudo, but Xcode doesn't prompt any LoadBungle pop up at launch, pretty weird... Any idea?

**Comment by matvdg** [comment]
@designatednerd I followed exactly the steps you told me and it worked! You're the best Ellen ♥️ Thanks!
