### ISSUE TITLE
xcode 12 support

### ISSUE THREAD

**Issue by nimerfarahty** [apollographql/xcode-graphql#34]
hello deras
is this plugin is supported on xcode 12 ?
Regards

**Comment by designatednerd** [comment]
Yes! Support was added with #33. Are you still having issues?

**Comment by KhaliqCitrusbits** [comment]
@designatednerd I am facing issue in XCode 12 GM Seed.

**Comment by nimerfarahty** [comment]
Hi dears
i try two method and it is not working

**Comment by designatednerd** [comment]
@nimerfarahty When you say two methods, do you mean trying both `setup.sh` and `setup-xcode11.sh`, or something else? 

Both of you, if you've previously installed the plugin, can you please delete the plugin and reinstall? We've seen some issues solved by doing that in the past.

**Comment by nimerfarahty** [comment]
thanks @designatednerd , what method should i use setup.sh or  setup-xcode11.sh ?

**Comment by designatednerd** [comment]
If you are using Xcode 11, setup-xcode11. If you are using 10 or 12, setup.sh.

**Comment by nimerfarahty** [comment]
i note that but both not working,   i follow the script code "setup-xcode11.sh" and apply the changes manually then it is worked thanks for your patience

**Comment by fernandomatal** [comment]
I just wanted to say that using the `sudo ./setup-xcode11.sh` also worked for me, the other setup.sh wasn't working with Xcode 12. Just if anyone else is encountering the same issue!

**Comment by designatednerd** [comment]
oof, good to know. I'll investigate if it got rebroken sometime during beta season 🤦‍♀️
