### ISSUE TITLE
Re-indent uses tabs when the project is set use spaces

### ISSUE THREAD

**Issue by CraigSiemens** [apollographql/xcode-graphql#39]
I'm not sure if this is an issue with Xcode 12.2 or the plugin but when I press `^I` (Editor > Structure > Re-indent), all the spaces used for indenting are changed to tabs.

Xcode shows shows that it should be using spaces in the File Inspector.
<img width="266" alt="Padded Screen Shot 2020-12-03 at 1 17 35 PM" src="https://user-images.githubusercontent.com/680442/101083578-f7ca4a80-3569-11eb-8bda-b3b516329b39.png">

**Comment by designatednerd** [comment]
If it's only on `.graphql` file's it's maaaaaaybe conceivably a thing that could be affected by our stuff, but if it's all files that's definitely Xcode.

**Comment by CraigSiemens** [comment]
It's only `.graphql` files.

I did some experimenting and here's what I found
- When the plugin isn't installed pressing tab inserts four spaces. (Re-indent doesn't work without the language plugin)
- After running `setup.sh`, pressing tab or reindent inserts a tab characters.
- After running `setup-xcode11.sh`, pressing tab or reindent inserts spaces.

Still doesn't really narrow it down to the plugin or Xcode but I thought it might be helpful.

**Comment by designatednerd** [comment]
and that's running `setup-xcode11.sh` but using Xcode 12?

**Comment by CraigSiemens** [comment]
Yeah, it's real confusing. But I guess one of those other files added into Xcode might be affecting it.

**Comment by designatednerd** [comment]
Yeah things are being put in different places because in Xcode 11, where you're supposed to put them didn't work at all, you had to go diving into private folders. 

I'll see if there's anything I can do.

**Comment by designatednerd** [comment]
I'm gonna go with probably not - in the [source code language plist file](https://github.com/apollographql/xcode-graphql/blob/e8e1ecd169dc7a6f5c08f2eb3bfce98955a4e474/Xcode.SourceCodeLanguage.GraphQL.plist#L38), we've set `requiresHardTabs` to `false`, and that's about the only reference I can find to anything related to tabs in any of the files associated with the plugin. 

I hate to be the "file a Radar" person, but...you probably ought to file a Radar on that.

**Comment by kimroen** [comment]
We're running into this same issue. When editing the graphql file xcode inserts tabs to reach the current indentation level and then adds spaces to adjust where the text is 2 spaces off the 4-space indentation level.

We're copying the operation from Apollo Studio and pasting into the graphql file in our project and then tweak in Xcode, which means we end up with a combination of tabs and spaces (which looks bizarre in GitHub which renders tabs as 8 spaces).

**Comment by designatednerd** [comment]
Haha I guess that's one way to take sides in the Tabs vs Spaces war... 

Unfortunately answer's still the same: There isn't anything I can find that's causing this - it looks like Xcode is ignoring the `requiresHardTabs` value we've set.

**Comment by kimroen** [comment]
> Haha I guess that's one way to take sides in the Tabs vs Spaces war...
> 
> Unfortunately answer's still the same: There isn't anything I can find that's causing this - it looks like Xcode is ignoring the `requiresHardTabs` value we've set.

No worries, just wanted to chime in in case there was anything. How are you dealing with this in your projects? Do you use tabs, perhaps? Do you not copy from Apollo Studio (or GraphQL Playground, etc…)?

I went looking for resources on how to deal with this, but almost everything I found pointed back at you as the source of knowledge on this topic, so I'm not going to investigate further unless there's a new lead 😅

**Comment by CraigSiemens** [comment]
It's just an issue with how Xcode plugins work. Pasting in from other sources could still have Xcode report it.

We ended up adding eslint using [eslint-plugin-graphql](https://github.com/apollographql/eslint-plugin-graphql) and prettier to ensure consistent formatting on these files. A slightly more heavy weight solution, but it works for us.

**Comment by mccarron** [comment]
@CraigSiemens @designatednerd did either of you file a radar, as I'll +1 it if you leave the radar number here.

Looking into doing eslint for now too to make sure this is fixed for all contributors.

**Comment by marcelofabri** [comment]
> I'm gonna go with probably not - in the [source code language plist file](https://github.com/apollographql/xcode-graphql/blob/e8e1ecd169dc7a6f5c08f2eb3bfce98955a4e474/Xcode.SourceCodeLanguage.GraphQL.plist#L38), we've set `requiresHardTabs` to `false`, and that's about the only reference I can find to anything related to tabs in any of the files associated with the plugin.
> 
> I hate to be the "file a Radar" person, but...you probably ought to file a Radar on that.

That file is not used in `setup.sh` though - but I'm not sure if there's somewhere within `~/Library/Xcode` that it can be added so it's recognized by Xcode.

**Comment by p4checo** [comment]
Well, following my findings in #42 I believe we might need to reinstante `setup-xcode11.sh` as the one setup mechanism 🤷🏼

**Comment by jpvajda** [comment]
Closing due to the age of this issue.
