### ISSUE TITLE
Xcode 15.0 (15A240d) broke GraphQL syntax highlight plugin, even after adding UUID

### ISSUE THREAD

**Issue by JoeFerrucci** [apollographql/xcode-graphql#53]
Xcode 15.0 (15A240d) broke this plugin. Even after adding the UUID to Info.plist

Steps: 
- Add UUID to plugin's Info.plist as directed in README.
- Launch Xcode
- Tap "Load Bundle" 
- Xcode crashes.
- Relaunch Xcode.
- Xcode crashes.
- Repeat launching Xcode...Xcode crashes.

Attached is partial crash report

<img width="1417" alt="Screenshot 2023-09-27 at 10 04 38 AM" src="https://github.com/apollographql/xcode-graphql/assets/2114494/1d336e99-449d-4591-ad27-6de510833175">

**Comment by JoeFerrucci** [comment]
@designatednerd @martijnwalraven @calvincestari anybody else having this issue?

**Comment by JoeFerrucci** [comment]
If I remove this key-value from the `GraphQL.xcplugindata`, file Xcode no longer crashes, but also the syntax highlight/format doesn't work either. 

![Screenshot 2023-10-10 at 9 47 25 AM](https://github.com/apollographql/xcode-graphql/assets/2114494/5fbccfac-25da-4424-b979-b3c52f357a09)

**Comment by calvincestari** [comment]
@JoeFerrucci - Ellen and Martijn are no longer maintainers of this repo. You can ping any of the [maintainers of apollo-ios](https://github.com/apollographql/apollo-ios#maintainers) for this repo too.

I've replicated the issue but I don't have a solution unfortunately. This tool is still built on the old Xcode plug-in architecture and it might finally be time to accept that Xcode 15 drops support for this and the only way forward is to rebuild this tool as an Xcode Extension instead. This work is not on our roadmap though so I don't have a timeline to share with you on when the tooling may work with Xcode 15.

**Comment by calvincestari** [comment]
I've updated the README to state that this tooling is not compatible with Xcode 15 and beyond.

**Comment by JoeFerrucci** [comment]
Great, thanks for update @AnthonyMDev @bignimbus @bobafetters

**Comment by jadar** [comment]
For what it's worth, the folks maintaining the Xcode Kotlin plugin found a [workaround](https://github.com/touchlab/xcode-kotlin/issues/96#issuecomment-1762368434).

**Comment by calvincestari** [comment]
Thanks @jadar, that's an interesting thread. It doesn't change the fact that the Xcode plug-in architecture is obsolete; the supported path forward for this repo has to be moving to the Xcode supported extensions architecture.

**Comment by jadar** [comment]
@calvincestari For sure, that makes a lot of sense. This could be a stop-gap measure though. 

In terms of the supported API, are there any docs for adding language definitions? I was looking into it the other day upon seeing this thread and wasn't seeing a clear path forward for how you'd do it the new way.

**Comment by calvincestari** [comment]
> In terms of the supported API, are there any docs for adding language definitions? I was looking into it the other day upon seeing this thread and wasn't seeing a clear path forward for how you'd do it the new way.

I'm not clear on how to do that myself. Xcode extensions are severely limited in what they can do unfortunately.

**Comment by TadeasKriz** [comment]
As far as I was looking into it, there was no way to add language specifications with the new Xcode extensions.

**Comment by jadar** [comment]
I received an update on my Feedback Assistant report. 

> Thank you for filing the feedback report. Please verify this issue with Xcode 15.1 beta 2 and update your bug report with your results by logging into https://feedbackassistant.apple.com/ or by using the Feedback Assistant app.
> 
> Xcode 15.1 beta 2 (15C5042i)
> https://developer.apple.com/download/
> Posted Date: October 26, 2023

I downloaded the new Xcode beta and added the new UUID to the plugin Plist file and installed it. It opens without crashing, and the syntax highlighting works. 🥳

**Comment by calvincestari** [comment]
Well that's good news! Maybe the plugin still has life left in it after all.

**Comment by jadar** [comment]
> Well that's good news! Maybe the plugin still has life left in it after all.

I hope this means that Apple will keep the legacy plugin architecture on life support until they add an official way to add language support. I don't know how you can add support for new languages, otherwise.

**Comment by JoeFerrucci** [comment]
Now that support is back in Xcode 15.1 should we revert this: https://github.com/apollographql/xcode-graphql/commit/488a1b7d6e5f9fabbf1c810e430ba13001238165 @calvincestari

**Comment by calvincestari** [comment]
Yes we can do that. Thanks for the reminder.
