### ISSUE TITLE
Cannot install add-on

### ISSUE THREAD

**Issue by vahotm** [apollographql/xcode-graphql#66]
Steps done:
 - `cd` into repo directory
 - perform `./setup.sh`
 - restart Xcode

After restarting Xcode nothing happens. Plugin and spec files exist at required locations: `~/Library/Developer/Xcode/Plug-ins/` and `~/Library/Developer/Xcode/Specifications/`.

Environment:
 - MacOS Ventura 13.6.4
 - Xcode 15.0.1

**Comment by calvincestari** [comment]
Try the latest Xcode (15.2), there were problems with the early versions of Xcode 15.

**Comment by vahotm** [comment]
Thanks @calvincestari, do you mean I need Xcode 15.2 to build the plugin or to use it with? I'm asking, because I use 15.0.1 for work.

**Comment by calvincestari** [comment]
To use it. There was a bug in the earlier versions of Xcode 15 that broke the plugins. From 15.1 it worked again.
