### ISSUE TITLE
Xcode 9.1 (9B55) issue

### ISSUE THREAD

**Issue by barus** [apollographql/xcode-graphql#7]
seems like plugin doesn't work with last Xcode version

**Comment by explicitcall** [comment]
reproducible for me as well

**Comment by martijnwalraven** [comment]
Unfortunately, every new Xcode version requires adding an updated `DVTPlugInCompatibilityUUID` to the plugin's `Info.plist`. I just added the one for Xcode 9.1, so that should fix this.

**Comment by explicitcall** [comment]
thanks a lot, that fixed it, this issue can be closed I think

**Comment by barus** [comment]
Fixed, thank you
